services:
  - name: stock-predictor
    type: web
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      pip install gunicorn  # Ensure Gunicorn is installed
    startCommand: gunicorn -w 4 -b 0.0.0.0:8000 app:app
    envVars:
      - key: PORT
        value: 8000
    autoDeploy: true
