services:
  - name: stock-predictor
    type: web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:5000 app:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: POLYGON_API_KEY
        sync: false
      - key: FINNHUB_API_KEY
        sync: false
